#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Init jenv
if which jenv > /dev/null; then eval "$(jenv init -)"; fi

export JAVA7_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home
export JAVA8_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-10.jdk/Contents/Home
export CATALINA_HOME=/Library/Tomcat

export ANDROID_SDK_ROOT=/usr/local/opt/android-sdk
export ANDROID_NDK=/usr/logs-incal/opt/android-ndk
export ANDROID_HOME=$ANDROID_SDK_ROOT

export GRADLE_HOME=/usr/local/opt/gradle
export GRADLE_OPTS="-Xmx1024M -Xms512M -XX:MaxPermSize=512M"

export J2OBJC_ROOT=/usr/local/Cellar/j2objcDist
export J2OBJC_HOME=$J2OBJC_ROOT/j2objc-1.2

export GROOVY_HOME=/usr/local/opt/groovy/libexec

# BasicTex tools
export PATH="/Library/TeX/texbin/:$PATH"

# Python Anaconda
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/usr/local/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/usr/local/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/usr/local/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/usr/local/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

